dist: trusty
sudo: false
language: python
  
matrix:
  include:
# --------------------- XPLAT builds ------------------------
    - python: 3.6
      env: &xplat-env
        - BUILD_OPTS=--xplat
        - NUNIT_PATH=~/.nuget/packages/nunit.consolerunner/3.*/tools/nunit3-console.exe
      addons: &xplat-addons
        apt:
          sources:
          - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
            key_url: https://packages.microsoft.com/keys/microsoft.asc
          - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
            key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
          packages:
            - mono-devel
            - ca-certificates-mono 
            #- dotnet-hostfxr-2.1.200
            #- dotnet-runtime-2.1.200
            - dotnet-sdk-2.1.200

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

addons:
  apt:
    sources:
      - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono

before_install:
  # Set-up dll path for embedded tests
  - PY_LIBDIR=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - export LD_LIBRARY_PATH=$PY_LIBDIR:$LD_LIBRARY_PATH
  # Addition to pythonnet build
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - python -m pip install -U pip
  - pip install -U setuptools wheel

install:
  - pip install -r requirements.txt
  # Install pythonnet
  - git clone https://github.com/pythonnet/pythonnet.git
  - cd pythonnet
  - python setup.py install $BUILD_OPTS
  - cd ..
  - pip install csharpy

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - ls cscode
  - ls cscode/machinelearning
  - python setup.py build_ext --inplace

script:
    - python setup.py unittests
